# Generated by Django 5.0.1 on 2024-01-19 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_BLog', '0003_remove_article_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='date',
            new_name='create_at',
        ),
    ]
