# Generated by Django 5.0.1 on 2024-01-19 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_BLog', '0004_rename_date_article_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='body',
            new_name='description',
        ),
    ]
