# Generated by Django 5.0.1 on 2024-01-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_BLog', '0007_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_at',
            field=models.DateTimeField(),
        ),
    ]
