# Generated by Django 5.0.1 on 2024-01-21 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_BLog', '0009_alter_article_create_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.RemoveField(
            model_name='article',
            name='create_at',
        ),
    ]
