# Generated by Django 5.0.1 on 2024-01-21 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_BLog', '0011_article_author_article_create_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
    ]
